version: '3.9'

services:

    captcha_bot:
        container_name: CaptchaBot
        image: captcha_bot

        build: .

        environment:
            - BOT_TOKEN=${BOT_TOKEN}
            - CHAT_ID_1=${CHAT_ID_1}
            - CHAT_ID_2=${CHAT_ID_2}
            - CHAT_ID_3=${CHAT_ID_3}
            - CHAT_ID_4=${CHAT_ID_4}

        ports:
            - "8443:443"

        volumes:
            - ./logs:/~/CaptchaBot/logs
            - ./users:/~/CaptchaBot/users

        restart: on-failure

volumes:
    logs:
    users:


# -------------------------------
# Create and start container:
# $ export BOT_TOKEN=<BOT_TOKEN>
# $ export CHAT_ID_1=<CHAT_ID_1>
# $ export CHAT_ID_2=<CHAT_ID_2>
# $ export CHAT_ID_3=<CHAT_ID_3>
# $ export CHAT_ID_4=<CHAT_ID_4>
# $ docker-compose up -d
# -------------------------------
# Stop lifted containers:
# $ docker-compose stop
# -------------------------------
# Start stopped containers
# $ docker-compose start
# -------------------------------
# Stop and delete containers and network:
# $ docker-compose down
# -------------------------------
# Remove image:
# $ docker rmi captcha_bot
# -------------------------------
# Clear logs & users:
# $ sudo rm -rf logs/*
# $ sudo rm -rf users/*
