name: Deploy to VPS

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run command on remote server
              uses: D3rHase/ssh-command-action@v0.2.2
              with:
                  host: ${{secrets.CAPTCHA_BOT_SSH_HOST}}
                  user: ${{secrets.CAPTCHA_BOT_SSH_USER}}
                  private_key: ${{secrets.CAPTCHA_BOT_SSH_PRIVATE_KEY}}
                  command: |
                      echo '--- START WORK ON REMOTE SERVER ---';
                      cd CaptchaBot;
                      echo '--- LIST OF FILES ---';
                      ls -al;
                      echo '--- GIT INFORMATION ---'
                      git checkout main;
                      git pull;
                      echo '--- DOCKER OPERATIONS ---';
                      docker-compose --file docker-compose.yml down;
                      docker rmi captcha_bot;
                      echo '--- LIST OF DOCKER CONTAINERS ---';
                      ps -a;
                      echo '--- UP CONTAINER ---';
                      export BOT_TOKEN=${{secrets.CAPTCHA_BOT_TOKEN}};
                      export CHAT_ID_1=${{vars.CHAT_ID_1}}
                      export CHAT_ID_2=${{vars.CHAT_ID_2}}
                      export CHAT_ID_3=${{vars.CHAT_ID_3}}
                      export CHAT_ID_4=${{vars.CHAT_ID_4}}
                      docker-compose --file docker-compose.yml up -d;
                      echo '--- DOCKER PRUNE ---';
                      docker system prune --all --force;
                      echo '--- LIST OF DOCKER CONTAINERS ---';
                      ps -a;
